INSERT INTO WEBDATA.PAY_METHOD(PAYMETHOD, PAYMETHOD_TEXT) VALUES('unionPay_zj', 'unionPay浙江');
INSERT INTO WEBDATA.PAY_METHOD(PAYMETHOD, PAYMETHOD_TEXT) VALUES('unionPay_sz', 'unionPay深圳');
INSERT INTO WEBDATA.PAY_METHOD(PAYMETHOD, PAYMETHOD_TEXT) VALUES('unionPay_bj', 'unionPay北京');
INSERT INTO WEBDATA.PAY_METHOD(PAYMETHOD, PAYMETHOD_TEXT) VALUES('unionPay_gz', 'unionPay广州');